version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    user: root
    working_dir: /app
    ports:
      - '8000:8000'
    networks:
      - app-network
  charts:
    build:
      context: ./charts
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge